// Code generated by go-swagger; DO NOT EDIT.

package feed

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/iAmPlus/microservice/models/apimodels"
)

// CreateFeedOKCode is the HTTP code returned for type CreateFeedOK
const CreateFeedOKCode int = 200

/*CreateFeedOK No content

swagger:response createFeedOK
*/
type CreateFeedOK struct {
}

// NewCreateFeedOK creates CreateFeedOK with default headers values
func NewCreateFeedOK() *CreateFeedOK {

	return &CreateFeedOK{}
}

// WriteResponse to the client
func (o *CreateFeedOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// CreateFeedBadRequestCode is the HTTP code returned for type CreateFeedBadRequest
const CreateFeedBadRequestCode int = 400

/*CreateFeedBadRequest Bad request <br>


swagger:response createFeedBadRequest
*/
type CreateFeedBadRequest struct {

	/*
	  In: Body
	*/
	Payload *apimodels.ErrorResponse `json:"body,omitempty"`
}

// NewCreateFeedBadRequest creates CreateFeedBadRequest with default headers values
func NewCreateFeedBadRequest() *CreateFeedBadRequest {

	return &CreateFeedBadRequest{}
}

// WithPayload adds the payload to the create feed bad request response
func (o *CreateFeedBadRequest) WithPayload(payload *apimodels.ErrorResponse) *CreateFeedBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create feed bad request response
func (o *CreateFeedBadRequest) SetPayload(payload *apimodels.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateFeedBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateFeedUnauthorizedCode is the HTTP code returned for type CreateFeedUnauthorized
const CreateFeedUnauthorizedCode int = 401

/*CreateFeedUnauthorized Unauthorized

swagger:response createFeedUnauthorized
*/
type CreateFeedUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *apimodels.ErrorResponse `json:"body,omitempty"`
}

// NewCreateFeedUnauthorized creates CreateFeedUnauthorized with default headers values
func NewCreateFeedUnauthorized() *CreateFeedUnauthorized {

	return &CreateFeedUnauthorized{}
}

// WithPayload adds the payload to the create feed unauthorized response
func (o *CreateFeedUnauthorized) WithPayload(payload *apimodels.ErrorResponse) *CreateFeedUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create feed unauthorized response
func (o *CreateFeedUnauthorized) SetPayload(payload *apimodels.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateFeedUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateFeedInternalServerErrorCode is the HTTP code returned for type CreateFeedInternalServerError
const CreateFeedInternalServerErrorCode int = 500

/*CreateFeedInternalServerError Internal error

swagger:response createFeedInternalServerError
*/
type CreateFeedInternalServerError struct {
}

// NewCreateFeedInternalServerError creates CreateFeedInternalServerError with default headers values
func NewCreateFeedInternalServerError() *CreateFeedInternalServerError {

	return &CreateFeedInternalServerError{}
}

// WriteResponse to the client
func (o *CreateFeedInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
