// Code generated by go-swagger; DO NOT EDIT.

package feed

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateFeedHandlerFunc turns a function with the right signature into a create feed handler
type CreateFeedHandlerFunc func(CreateFeedParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateFeedHandlerFunc) Handle(params CreateFeedParams) middleware.Responder {
	return fn(params)
}

// CreateFeedHandler interface for that can handle valid create feed params
type CreateFeedHandler interface {
	Handle(CreateFeedParams) middleware.Responder
}

// NewCreateFeed creates a new http.Handler for the create feed operation
func NewCreateFeed(ctx *middleware.Context, handler CreateFeedHandler) *CreateFeed {
	return &CreateFeed{Context: ctx, Handler: handler}
}

/*CreateFeed swagger:route POST /feed-post feed createFeed

post feed

postfeed

*/
type CreateFeed struct {
	Context *middleware.Context
	Handler CreateFeedHandler
}

func (o *CreateFeed) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateFeedParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
