// Code generated by go-swagger; DO NOT EDIT.

package feed

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/iAmPlus/microservice/models/apimodels"
)

// FriendsFeedOKCode is the HTTP code returned for type FriendsFeedOK
const FriendsFeedOKCode int = 200

/*FriendsFeedOK Successfully user feed

swagger:response friendsFeedOK
*/
type FriendsFeedOK struct {

	/*
	  In: Body
	*/
	Payload *apimodels.FriendsFeed `json:"body,omitempty"`
}

// NewFriendsFeedOK creates FriendsFeedOK with default headers values
func NewFriendsFeedOK() *FriendsFeedOK {

	return &FriendsFeedOK{}
}

// WithPayload adds the payload to the friends feed o k response
func (o *FriendsFeedOK) WithPayload(payload *apimodels.FriendsFeed) *FriendsFeedOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the friends feed o k response
func (o *FriendsFeedOK) SetPayload(payload *apimodels.FriendsFeed) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FriendsFeedOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FriendsFeedBadRequestCode is the HTTP code returned for type FriendsFeedBadRequest
const FriendsFeedBadRequestCode int = 400

/*FriendsFeedBadRequest Bad request <br>


swagger:response friendsFeedBadRequest
*/
type FriendsFeedBadRequest struct {

	/*
	  In: Body
	*/
	Payload *apimodels.ErrorResponse `json:"body,omitempty"`
}

// NewFriendsFeedBadRequest creates FriendsFeedBadRequest with default headers values
func NewFriendsFeedBadRequest() *FriendsFeedBadRequest {

	return &FriendsFeedBadRequest{}
}

// WithPayload adds the payload to the friends feed bad request response
func (o *FriendsFeedBadRequest) WithPayload(payload *apimodels.ErrorResponse) *FriendsFeedBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the friends feed bad request response
func (o *FriendsFeedBadRequest) SetPayload(payload *apimodels.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FriendsFeedBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FriendsFeedUnauthorizedCode is the HTTP code returned for type FriendsFeedUnauthorized
const FriendsFeedUnauthorizedCode int = 401

/*FriendsFeedUnauthorized Unauthorized

swagger:response friendsFeedUnauthorized
*/
type FriendsFeedUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *apimodels.ErrorResponse `json:"body,omitempty"`
}

// NewFriendsFeedUnauthorized creates FriendsFeedUnauthorized with default headers values
func NewFriendsFeedUnauthorized() *FriendsFeedUnauthorized {

	return &FriendsFeedUnauthorized{}
}

// WithPayload adds the payload to the friends feed unauthorized response
func (o *FriendsFeedUnauthorized) WithPayload(payload *apimodels.ErrorResponse) *FriendsFeedUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the friends feed unauthorized response
func (o *FriendsFeedUnauthorized) SetPayload(payload *apimodels.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FriendsFeedUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// FriendsFeedInternalServerErrorCode is the HTTP code returned for type FriendsFeedInternalServerError
const FriendsFeedInternalServerErrorCode int = 500

/*FriendsFeedInternalServerError Internal error

swagger:response friendsFeedInternalServerError
*/
type FriendsFeedInternalServerError struct {
}

// NewFriendsFeedInternalServerError creates FriendsFeedInternalServerError with default headers values
func NewFriendsFeedInternalServerError() *FriendsFeedInternalServerError {

	return &FriendsFeedInternalServerError{}
}

// WriteResponse to the client
func (o *FriendsFeedInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
