// Code generated by go-swagger; DO NOT EDIT.

package feed

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetRelatedFeedHandlerFunc turns a function with the right signature into a get related feed handler
type GetRelatedFeedHandlerFunc func(GetRelatedFeedParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRelatedFeedHandlerFunc) Handle(params GetRelatedFeedParams) middleware.Responder {
	return fn(params)
}

// GetRelatedFeedHandler interface for that can handle valid get related feed params
type GetRelatedFeedHandler interface {
	Handle(GetRelatedFeedParams) middleware.Responder
}

// NewGetRelatedFeed creates a new http.Handler for the get related feed operation
func NewGetRelatedFeed(ctx *middleware.Context, handler GetRelatedFeedHandler) *GetRelatedFeed {
	return &GetRelatedFeed{Context: ctx, Handler: handler}
}

/*GetRelatedFeed swagger:route POST /relates feed getRelatedFeed

related feed

related feed response

*/
type GetRelatedFeed struct {
	Context *middleware.Context
	Handler GetRelatedFeedHandler
}

func (o *GetRelatedFeed) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetRelatedFeedParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
