// Code generated by go-swagger; DO NOT EDIT.

package apimodels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RelatedFeed list of Users structure
//
// swagger:model related_feed
type RelatedFeed struct {

	// actor
	Actor string `json:"actor,omitempty"`

	// verb
	Verb string `json:"verb,omitempty"`

	// object
	Object string `json:"object,omitempty"`

	// target
	Target string `json:"target,omitempty"`

	// related
	Related []*FeedPost `json:"related"`
}

// Validate validates this related feed
func (m *RelatedFeed) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRelated(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RelatedFeed) validateRelated(formats strfmt.Registry) error {

	if swag.IsZero(m.Related) { // not required
		return nil
	}

	for i := 0; i < len(m.Related); i++ {
		if swag.IsZero(m.Related[i]) { // not required
			continue
		}

		if m.Related[i] != nil {
			if err := m.Related[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("related" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *RelatedFeed) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RelatedFeed) UnmarshalBinary(b []byte) error {
	var res RelatedFeed
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
